* cpvirtualenv working now * The previous technique of using $_ to get the path to virtualenvwrapper.csh   doesn't work if it's source from within .cshrc or the like.  The only other   way I can think of is to require the script's own path to be passed to it as   an argument; annoying, but as long as it's documented no one should have   trouble with it.

diff --git a/.virtualenvwrapper.csh/virtualenvwrapper_initialize b/.virtualenvwrapper.csh/virtualenvwrapper_initialize
--- a/.virtualenvwrapper.csh/virtualenvwrapper_initialize
+++ b/.virtualenvwrapper.csh/virtualenvwrapper_initialize
@@ -3,18 +3,18 @@ setenv WORKON_HOME "`virtualenvwrapper_derive_workon_home`"
 virtualenvwrapper_verify_workon_home -q || exit 1
 
 # Set the location of the hook scripts
-if ( $?VIRTUALENVWRAPPER_HOOK_DIR ) then
+if ( ! $?VIRTUALENVWRAPPER_HOOK_DIR ) then
     setenv VIRTUALENVWRAPPER_HOOK_DIR "$WORKON_HOME"
 endif
 
 # Set the location of the hook script logs
-if ( $?VIRTUALENVWRAPPER_LOG_DIR ) then
+if ( ! $?VIRTUALENVWRAPPER_LOG_DIR ) then
     setenv VIRTUALENVWRAPPER_LOG_DIR "$WORKON_HOME"
 endif
 
 virtualenvwrapper_run_hook "initialize"
 if ( $? != 0 ) then
-    echo "virtualenvwrapper.sh: There was a problem running the initialization hooks. If Python could not import the module virtualenvwrapper.hook_loader, check that virtualenv has been installed for VIRTUALENVWRAPPER_PYTHON=$VIRTUALENVWRAPPER_PYTHON and that PATH is set properly." > /dev/stderr
+    echo "virtualenvwrapper.csh: There was a problem running the initialization hooks. If Python could not import the module virtualenvwrapper.hook_loader, check that virtualenv has been installed for VIRTUALENVWRAPPER_PYTHON=$VIRTUALENVWRAPPER_PYTHON and that PATH is set properly." > /dev/stderr
     exit 1
 endif
 
